name: CI/CD for Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js App
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Production
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out
